{% set name = "opencv-python-headless" %}
{% set version = "4.11.0.86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opencv-python-headless-{{ version }}.tar.gz
  sha256: 996eb282ca4b43ec6a3972414de0e2331f5d9cda2b41091a49739c19fb843798

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  missing_dso_whitelist:  # [linux]
    - /lib64/ld-linux-x86-64.so.2  # [linux]
    - /lib64/libc.so.6  # [linux]
    - /lib64/libdl.so.2  # [linux]
    - /lib64/libm.so.6  # [linux]
    - /lib64/libpthread.so.0  # [linux]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ stdlib('c') }}  # [not win]
    - cmake
    - make  # [unix]
  host:
    - python
    - sysroot_linux-64  # [linux]
    - libgcc-ng  # [linux]
    - numpy ==1.13.3  # [py==36]
    - numpy ==1.17.0  # [py==37]
    - numpy ==1.17.5  # [py==38]
    - numpy ==1.19.3  # [py<39 and linux]
    - numpy ==1.21.0  # [py<39 and darwin]
    - numpy >=2.0.0  # [py>=39]
    - packaging
    - pip
    - scikit-build >=0.14.0
    - setuptools >=59.2.0  # [py<312]
    - setuptools <70.0.0  # [py>=312]
  run:
    - cmake
    - python
    - sysroot_linux-64  # [linux]
    - libgcc-ng  # [linux]
    - numpy >=1.13.3  # [py<37]
    - numpy >=1.21.0  # [py<=39 and osx]
    - numpy >=1.21.2  # [py>=310]
    - numpy >=1.21.4  # [py>=310 and osx]
    - numpy >=1.23.5  # [py>=311]
    - numpy >=1.26.0  # [py>=312]
    - numpy >=1.19.3  # [py>=36 and linux]
    - numpy >=1.17.0  # [py>=37]
    - numpy >=1.17.3  # [py>=38]
    - numpy >=1.19.3  # [py>=39]

test:
  imports:
    - cv2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opencv/opencv-python
  summary: Wrapper package for OpenCV python bindings.
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-3RD-PARTY.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - nilchia
